# Generated by Django 5.2 on 2025-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_instructorprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rank",
            field=models.CharField(
                choices=[
                    ("SGT", "Sergeant"),
                    ("CPL", "Corporal"),
                    ("SPTE", "Private"),
                    ("WOII", "Warrant Officer II"),
                    ("PTE", "Private"),
                    ("LCPL", "Lance Corporal"),
                    ("WOI", "Warrant Officer I"),
                    ("2LT", "Second Lieutenant"),
                    ("LT", "Lieutenant"),
                    ("CAPT", "Captain"),
                    ("MAJ", "Major"),
                    ("LT COL", "Lieutenant Colonel"),
                    ("COL", "Colonel"),
                ],
                max_length=20,
            ),
        ),
    ]
